'use client';
import {useEffect,useRef,useState} from 'react';
import {AnimatePresence,MotionConfig,motion} from 'motion/react';
import {asset,nav,services,companies,stages,systems,contact,directExperience} from '@/lib/content';
import {Arrow,CvLink,Label,Magnetic,useDialog} from './Primitives';
import Markets from './Markets';
import CvViewer from './CvViewer';
const number=(n:number)=>String(n+1).padStart(2,'0');
function Portrait(){const [error,setError]=useState(false);return error?<div className="portrait-placeholder">Abdulrahman<br/><i>Zidan.</i></div>:<img src={asset('profile.webp')} width="640" height="640" alt="Abdulrahman Zidan, wearing glasses and a black blazer" fetchPriority="high" onError={()=>setError(true)}/>;}
function Asterisk(){return <svg viewBox="0 0 80 80" fill="none" aria-hidden="true">{[0,45,90,135].map(r=><path key={r} d="M40 3V77" stroke="currentColor" strokeWidth="2" transform={`rotate(${r} 40 40)`}/>)}</svg>;}
function Swap({id,children}:{id:number;children:React.ReactNode}){return <AnimatePresence mode="wait"><motion.div key={id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.2}}>{children}</motion.div></AnimatePresence>;}
export default function Portfolio(){
 const [active,setActive]=useState('top'),[menu,setMenu]=useState(false),[command,setCommand]=useState(false),[query,setQuery]=useState('');
 const [service,setService]=useState(0),[company,setCompany]=useState(0),[stage,setStage]=useState(0),[tool,setTool]=useState(0);
 const [film,setFilm]=useState(false),[mediaError,setMediaError]=useState(false),[fullscreenNote,setFullscreenNote]=useState(''),[reduced,setReduced]=useState(false),[manualReduced,setManualReduced]=useState(false);
 const motionReduced=reduced||manualReduced;
 useEffect(()=>{document.documentElement.dataset.motion=motionReduced?'reduce':'normal';},[motionReduced]);
 const restoreFilmFocus=useRef(false);
 const menuRef=useRef<HTMLDialogElement>(null),commandRef=useRef<HTMLDialogElement>(null),cursor=useRef<HTMLDivElement>(null),video=useRef<HTMLVideoElement>(null),filmTrigger=useRef<HTMLButtonElement>(null);
 const closeMenu=useRef(()=>setMenu(false)).current,closeCommand=useRef(()=>setCommand(false)).current;
 useDialog(menu,menuRef,closeMenu);useDialog(command,commandRef,closeCommand);
 useEffect(()=>{
  const sections=[...document.querySelectorAll<HTMLElement>('main section[id]')];
  const media=matchMedia('(prefers-reduced-motion: reduce)');const motionChange=()=>setReduced(media.matches);motionChange();media.addEventListener('change',motionChange);
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('entered');}),{threshold:.12});sections.forEach(s=>observer.observe(s));
  let frame=0;const update=()=>{frame=0;let id='top';for(const s of sections)if(s.getBoundingClientRect().top<=innerHeight*.36)id=s.id;setActive(id);const max=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--page-progress',String(max>0?scrollY/max:0));document.documentElement.style.setProperty('--portrait-shift',`${Math.min(28,scrollY*.04)}px`);};
  const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};
  const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setQuery('');setCommand(v=>!v);}if(e.key==='Escape'){restoreFilmFocus.current=true;setFilm(false);}};
  const pointer=(e:PointerEvent)=>{if(!cursor.current)return;cursor.current.style.transform=`translate3d(${e.clientX+16}px,${e.clientY+18}px,0)`;const t=(e.target as Element).closest<HTMLElement>('[data-cursor]');cursor.current.textContent=t?.dataset.cursor||'';cursor.current.dataset.visible=String(!!t);};
  window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('keydown',key);window.addEventListener('pointermove',pointer,{passive:true});update();
  return ()=>{observer.disconnect();cancelAnimationFrame(frame);media.removeEventListener('change',motionChange);window.removeEventListener('scroll',scroll);window.removeEventListener('keydown',key);window.removeEventListener('pointermove',pointer);};
 },[]);
 useEffect(()=>{if(cursor.current)cursor.current.dataset.visible='false';if(film){setMediaError(false);setFullscreenNote('');}else video.current?.pause();},[film]);
 const go=(id:string)=>{setMenu(false);setCommand(false);location.hash=id;};
 const openFilm=()=>{setFilm(true);go('introduction');};
 const closeFilm=()=>{restoreFilmFocus.current=true;setFilm(false);};
 const fullscreen=async()=>{try{await video.current?.requestFullscreen();}catch{setFullscreenNote('Fullscreen is unavailable in this browser. The video can still play here.');}};
 const commands=[...nav.map(name=>({name,action:()=>go(name.toLowerCase())})),{name:'Play introduction',action:openFilm},{name:'View CV',action:()=>go('cv')},{name:'LinkedIn',action:()=>window.open(contact.linkedin,'_blank','noreferrer')},{name:'Telegram',action:()=>window.open(contact.telegram,'_blank','noreferrer')}];
 return <MotionConfig reducedMotion={motionReduced?'always':'user'}><a className="skip-link" href="#about">Skip to content</a><div ref={cursor} className="editor-cursor" aria-hidden="true"/><div className="page-progress" aria-hidden="true"/>
 <header className="header"><a className="masthead" href="#top" aria-label="The Zidan Edit — home">THE ZIDAN <i>EDIT</i><span>THE PERSON. THE PRACTICE.</span></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(name=><a key={name} href={`#${name.toLowerCase()}`} aria-current={active===name.toLowerCase()?'location':undefined}>{name}</a>)}</nav><div className="header-actions"><button className="command-toggle" aria-label="Open command menu" onClick={()=>{setQuery('');setCommand(true);}}>⌘ K</button><a className="hire" href="#contact">LET’S TALK <Arrow diagonal/></a><button className="menu-toggle" aria-label="Open navigation" onClick={()=>setMenu(true)}>INDEX <span>☰</span></button></div></header>
 <main><section id="top" className="hero"><div className="edition-line"><span>PERSONAL EDITION / SALES & SYSTEMS</span><span>CAIRO, EGYPT ↔ U.S. TEAMS</span><span className="availability"><i/> AVAILABLE FOR REMOTE WORK</span></div><div className="hero-spread"><div className="hero-copy"><p className="eyebrow">REAL ESTATE SALES & LEAD MANAGEMENT</p><h1><span className="first-name">Abdulrahman</span><span className="last-name">Zidan<span>.</span></span></h1><div className="hero-deck"><span className="editor-mark" aria-hidden="true">[ A.Z ]</span><p>Good conversations.<br/><i>Better next steps.</i></p></div><p className="hero-description">I connect with people, find the opportunity,<br className="desktop-break"/> and keep the context moving forward.</p><div className="hero-actions"><Magnetic href="#contact" className="ink-button">LET’S WORK TOGETHER <Arrow diagonal/></Magnetic><CvLink className="text-link"/></div><div className="hero-note"><span>THE SHORT VERSION</span><p>Cold Caller. Lead Manager.<br/>Appointment Setter. Virtual Assistant.</p></div></div><div className="cover-composition"><div className="cover-caption"><span>FIG. 01 / THE PERSON</span><span>A CONVERSATION STARTS HERE.</span></div><div className="cover-frame" data-cursor="MEET"><Portrait/><div className="portrait-annotation"><span>ABDULRAHMAN ZIDAN</span><i>Human first.</i></div><button className="cover-play" aria-label="Play introduction" onClick={openFilm} data-cursor="PLAY"><span className="play-icon">▶</span><span>MEET THE PERSON<br/><small>01:08 / INTRODUCTION</small></span><Arrow diagonal/></button></div><div className="margin-annotation">A LITTLE CONTEXT GOES A LONG WAY.</div><div className="editor-seal"><Asterisk/></div><div className="cover-foot"><span>PORTRAIT / CAIRO</span><span>01 — THE ZIDAN EDIT</span></div></div></div><div className="hero-bottom"><a href="#about">TURN THE PAGE <span>↓</span></a><p>People. Context. Ownership.</p><span>A PERSONAL APPROACH TO PROFESSIONAL WORK.</span></div></section>
 <section id="about" className="chapter about"><Label number="01">THE PERSON BEHIND THE WORK</Label><div className="about-spread"><aside className="margin-note"><span className="eyebrow">EDITOR’S NOTE</span><p>Not another caller<br/>reading a script.</p><Asterisk/><span>COMMUNICATION<br/>WITH CONTEXT.</span></aside><div className="about-main"><h2>The work is sales.<br/>The starting point<br/>is <i>always people.</i></h2><div className="article-columns"><p className="drop-cap">I bring 3+ years of U.S. real estate cold-calling experience, with approximately one year of hands-on Lead Manager work with U.S. clients and investors. {directExperience}</p><p>From seller motivation to the next follow-up, I keep the conversation human and the context clear. Experience in real estate and solar has taught me how those fundamentals transfer across industries.</p></div><div className="about-foot"><p><span className="eyebrow">A MIND FOR SYSTEMS, TOO</span>Computer Science student<br/>Modern Academy for Computer Science and Technology.</p><CvLink className="text-link"/></div></div></div></section>
 <section id="services" className="chapter services"><Label number="02">WAYS TO WORK TOGETHER</Label><div className="chapter-heading"><h2>One practice.<br/><i>Four ways forward.</i></h2><p>The role can change. Communication,<br/>qualification and ownership stay.</p></div><div className="services-spread"><div className="service-index" role="tablist" aria-label="Services" aria-orientation="vertical">{services.map((s,i)=><button key={s.name} id={`service-tab-${i}`} role="tab" aria-selected={service===i} aria-controls="service-panel" tabIndex={service===i?0:-1} onClick={()=>setService(i)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?services.length-1:(i+(e.key==='ArrowDown'?1:-1)+services.length)%services.length;setService(next);document.getElementById(`service-tab-${next}`)?.focus();}}}><span>{number(i)}</span><span>{s.name}</span><Arrow diagonal/></button>)}</div><div className="service-article" id="service-panel" role="tabpanel" aria-labelledby={`service-tab-${service}`}><Swap id={service}><div className="article-metadata"><span>THE PRACTICE / {number(service)}</span><span>ROLE & VALUE</span></div><span className="article-number" aria-hidden="true">{number(service)}</span><h3>{services[service].verb}</h3><p>{services[service].text}</p><ul>{services[service].details.map(d=><li key={d}><span>↗</span>{d}</li>)}</ul><a href="#contact" className="text-link">LET’S TALK ABOUT THIS ROLE <Arrow diagonal/></a></Swap></div></div></section>
 <section id="method" className="chapter method"><Label number="03">NOTES ON THE METHOD</Label><div className="method-spread"><div className="sticky-caption"><p className="eyebrow">FROM FIRST HELLO<br/>TO CLEAN HANDOFF.</p><h2>Every lead<br/>deserves a<br/><i>next chapter.</i></h2><p className="method-copy">Explore the steps.<br/>The context belongs with the lead.</p><svg className="method-ribbon" viewBox="0 0 340 130" fill="none" aria-hidden="true"><path d="M4 80 C80 80,75 15,145 15 S255 115,335 65" stroke="currentColor" strokeWidth="1.5"/>{!motionReduced&&<circle r="4" fill="currentColor"><animateMotion dur="6s" repeatCount="indefinite" path="M4 80 C80 80,75 15,145 15 S255 115,335 65"/></circle>}</svg></div><div className="method-index">{stages.map((s,i)=><button key={s.name} className={stage===i?'selected':''} aria-expanded={stage===i} onClick={()=>setStage(i)}><span className="step-number">{number(i)}</span><span className="step-body"><strong>{s.name}</strong><span>{s.text}</span><AnimatePresence initial={false}>{stage===i&&<motion.span className="step-note" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{s.detail}</motion.span>}</AnimatePresence></span><span className="step-sign">{stage===i?'−':'+'}</span></button>)}</div></div></section>
 <section id="experience" className="chapter experience"><Label number="04">EXPERIENCE, IN CONTEXT</Label><div className="chapter-heading"><h2>From the first call<br/>to <i>pipeline ownership.</i></h2><p>U.S. real estate + solar.<br/>Different environments. Shared fundamentals.</p></div><div className="career-line"><div><strong>3+ years</strong><span>COLD CALLING</span></div><span className="career-arrow" aria-hidden="true">⟶</span><div><strong>~1 year</strong><span>HANDS-ON LEAD MANAGEMENT</span></div><p>Qualify. Follow up.<br/>Prepare the next conversation.</p></div><div className="direct-experience"><span>2+ YEARS / DIRECT COLLABORATION</span><p>{directExperience}</p></div><div className="experience-spread"><div className="company-index" aria-label="Companies and teams">{companies.map((c,i)=><button key={c.name} aria-pressed={company===i} onClick={()=>setCompany(i)}><span>{number(i)}</span><span>{c.name}</span><Arrow diagonal/></button>)}</div><div className="company-article" aria-live="polite"><Swap id={company}><div className="article-metadata"><span>SELECTED EXPERIENCE</span><span>{number(company)} / 07</span></div><h3>{companies[company].name}<i>.</i></h3><span className="company-rule"/><p>{companies[company].text}</p><div className="company-tags"><span>COMMUNICATION</span><span>QUALIFICATION</span><span>FOLLOW-THROUGH</span></div><span className="company-endnote">A chapter in the same practice:<br/><i>people, context & the next action.</i></span></Swap></div></div></section>
 <Markets editorial/>
 <section id="proof" className="chapter proof"><Label number="06">THE FACTS, WITHOUT THE FICTION</Label><div className="chapter-heading"><h2>Grounded<br/>in <i>the work.</i></h2><p>Experience over inflated numbers.<br/>A few things worth knowing.</p></div><div className="proof-ledger"><div><strong>3<span>+</span></strong><h3>Years in U.S. real estate</h3><p>Homeowner conversations, seller qualification and consistent follow-up.</p></div><div><strong>02</strong><h3>Core industries</h3><p>Real estate and solar. Shared fundamentals, different conversations.</p></div><div><strong className="proof-words">Caller<br/><i>to manager.</i></strong><h3>A progression in ownership</h3><p>From generating the lead to managing the context and the next action.</p></div></div><div className="proof-note"><Asterisk/><p>Recognized as a top achiever.<br/>Usually met or exceeded performance expectations.</p><span>NO INFLATED METRICS.<br/>JUST THE RELEVANT CONTEXT.</span></div></section>
 <section id="systems" className="chapter systems"><Label number="07">THE TOOLS BEHIND THE PRACTICE</Label><div className="systems-spread"><div className="system-heading"><h2>Human<br/>conversation.<br/><i>Clear systems.</i></h2><p>The tools can change. I learn the stack,<br/>keep the data clean and make the<br/>next action obvious.</p><span className="system-margin">PEOPLE → CONTEXT → ACTION</span></div><div className="system-library"><div className="tool-index" aria-label="Explore systems">{systems.map((s,i)=><button key={s.name} aria-pressed={tool===i} onClick={()=>setTool(i)}><span>{s.name}</span><span>{s.group}</span><Arrow diagonal/></button>)}</div><div className="tool-note" aria-live="polite"><Swap id={tool}><span className="eyebrow">WORKING NOTE / {systems[tool].label}</span><h3>{systems[tool].name}</h3><p>{systems[tool].text}</p></Swap></div></div></div></section>
 <section id="introduction" className={`chapter introduction ${film?'film-open':''}`}><Label number="08">ON THE OTHER END OF THE LINE</Label><div className="chapter-heading"><h2>A face. A voice.<br/><i>A better introduction.</i></h2><p>A little over a minute.<br/>A better sense of who you’ll work with.</p></div><motion.div layout className="identity-card" data-cursor={film?undefined:'PLAY'} transition={{duration:motionReduced?0:.6,ease:[.22,1,.36,1]}}><AnimatePresence mode="wait" initial={false}>{film?<motion.div key="screen" className="film-screen" initial={{opacity:0,clipPath:'inset(0 0 100% 0)'}} animate={{opacity:1,clipPath:'inset(0 0 0% 0)'}} exit={{opacity:0}} transition={{duration:motionReduced?0:.55}}><div className="film-heading"><span>THE ZIDAN EDIT / IN CONVERSATION</span><button onClick={closeFilm} aria-label="Close introduction">CLOSE <span>×</span></button></div><video ref={video} controls playsInline autoPlay preload="metadata" tabIndex={0} onLoadedData={()=>video.current?.focus({preventScroll:true})} poster={asset('intro-poster.jpg')} onError={()=>setMediaError(true)}><source src={asset('intro.mp4')} type="video/mp4" onError={()=>setMediaError(true)}/></video>{mediaError&&<p className="media-error">The introduction is temporarily unavailable. <a href={`mailto:${contact.email}`}>Start a conversation by email ↗</a></p>}<div className="film-foot"><span>01:07 / ABDULRAHMAN ZIDAN</span><button onClick={fullscreen}>FULLSCREEN <Arrow diagonal/></button></div>{fullscreenNote&&<p className="fullscreen-note" role="status">{fullscreenNote}</p>}</motion.div>:<motion.button ref={filmTrigger} onAnimationComplete={()=>{if(restoreFilmFocus.current){filmTrigger.current?.focus({preventScroll:true});restoreFilmFocus.current=false;}}} key="identity" className="identity-trigger" onClick={()=>setFilm(true)} aria-label="Play Abdulrahman’s introduction" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.2}}><div className="identity-image"><img src={asset('intro-poster.jpg')} width="1280" height="720" loading="lazy" alt="Abdulrahman speaking in his introduction video"/><span className="identity-img-caption">MOVING PORTRAIT / 01</span><span className="large-play">▶</span></div><div className="identity-copy"><span className="eyebrow">A PERSONAL INTRODUCTION</span><p>Meet<br/><i>Abdulrahman.</i></p><span className="identity-time">01:07 <span>REAL CONVERSATIONS.<br/>REAL CONTEXT.</span></span><span className="identity-action">OPEN THE CONVERSATION <Arrow diagonal/></span></div></motion.button>}</AnimatePresence></motion.div><div className="cv-strip"><div><span className="eyebrow">THE FULL BACKGROUND</span><p>Conversation first.<br/><i>Credentials close by.</i></p></div><CvLink className="cv-button"/></div></section>
 <CvViewer editorial/>
 <section id="contact" className="chapter contact"><Label number="10">THE NEXT CONVERSATION</Label><div className="contact-top"><span className="availability"><i/> AVAILABLE FOR REMOTE WORK</span><span>CAIRO, EGYPT / WORKING WITH U.S. TEAMS</span></div><h2>Let’s make the next<br/>conversation <i>count.</i><span className="contact-star"><Asterisk/></span></h2><a className="contact-email" href={`mailto:${contact.email}`} data-cursor="EMAIL">{contact.email}<Arrow diagonal/></a><div className="contact-bottom"><div className="inline-links"><a href={contact.linkedin} target="_blank" rel="noreferrer">LINKEDIN <Arrow diagonal/></a><a href={contact.telegram} target="_blank" rel="noreferrer">TELEGRAM <Arrow diagonal/></a><CvLink/><button onClick={openFilm}>INTRODUCTION <Arrow diagonal/></button></div><span>READY FOR THE RIGHT TEAM.<br/>READY FOR THE NEXT CHAPTER.</span></div></section>
 </main><footer><a className="footer-brand" href="#top">The Zidan <i>Edit.</i></a><span>© {new Date().getFullYear()} ABDULRAHMAN ZIDAN</span><span>A PERSONAL EDITION. A PROFESSIONAL PRACTICE.</span><button className="motion-toggle" aria-pressed={motionReduced} disabled={reduced} onClick={()=>setManualReduced(v=>!v)}>{reduced?'SYSTEM: REDUCED MOTION':manualReduced?'ENABLE MOTION':'REDUCE MOTION'}</button><a href="#top">BACK TO THE COVER ↑</a></footer>
 <dialog ref={menuRef} className="menu-dialog" aria-labelledby="menu-title"><div className="dialog-heading"><h2 id="menu-title">The <i>index.</i></h2><button className="close-button" aria-label="Close navigation" onClick={closeMenu}>×</button></div><nav aria-label="Mobile navigation">{nav.map((name,i)=><a key={name} href={`#${name.toLowerCase()}`} onClick={closeMenu}><span>{number(i)}</span>{name}<Arrow diagonal/></a>)}</nav><a className="ink-button" href="#contact" onClick={closeMenu}>LET’S WORK TOGETHER <Arrow diagonal/></a></dialog>
 <dialog ref={commandRef} className="command-dialog" aria-labelledby="command-title"><div className="dialog-heading"><h2 id="command-title">Find your <i>chapter.</i></h2><button className="close-button" aria-label="Close command menu" onClick={closeCommand}>×</button></div><label className="sr-only" htmlFor="chapter-search">Search chapters</label><input autoFocus id="chapter-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search chapters, CV, links…"/><div className="command-results">{commands.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.name} onClick={()=>{setCommand(false);c.action();}}>{c.name}<Arrow diagonal/></button>)}{!commands.some(c=>c.name.toLowerCase().includes(query.toLowerCase()))&&<p>No chapter found. Try “CV” or “Introduction”.</p>}</div><span className="command-help">ESC TO CLOSE / TAB TO EXPLORE</span></dialog>
 </MotionConfig>;
}
